### ISSUE TITLE
Add support of global kube-slack channel configuration.

### ISSUE THREAD

**Issue by omerozery** [wongnai/kube-slack#36]
it will be nice if one can configure slack channel (with slack token) globally in the kube-slack deployment, it is much more convenient, to change channel name between deployments then slack_url.

**Comment by whs** [comment]
I'm not sure I understand this request.

If you want to change Slack channel, then you can do so by configuring your incoming webhooks channel.

The `kube-slack/slack-channel` annotation is for overriding the above configuration for specific pods and is not required.

**Comment by omerozery** [comment]
OK, i will try to explain, maybe i'm mistaken due to my lack of knowledge in slack.

1. i have 9 namespaces across 4 clusters, with 22 deployments each, to taint every pod with kube-```slack/slack-channel``` is out of the question, all the more so when i need it globally configured per cluster, it seems very inefficient to use the 'specific pods annotations' feature. (from what i understand it is impossible to configure multiple channels per incoming webhook, and even if it is possible there is no environment variable in kube-slack deployment for changing the channel)

2. Although i can create 4 Incoming WebHooks (1 for each cluster) and place their URL in each of the kube-slack deployments, i will have to maintain some kind of map (SLACK_URL vs CLUSER_NAME), which turns to be very clumsy, and i want to keep my cluster's deployment and management logic to a minimum, like i did so far with any organization-wide tool that has to be per cluster configured.

* the only thing that changes between clusters is the CLUSTER_NAME which can also be used as SLACK_CHANNEL (or some kind of string manipulation of it). if i cloud change only the SLACK_CHANNEL when i deploy kube-slack as part of single k8s cluster deployment process.

hope that it explains the reason.

**Comment by whs** [comment]
I just added SLACK_CHANNEL option in master. Could you please try the image with latest tag?

**Comment by omerozery** [comment]
thanks! i will check it today and let you know

**Comment by omerozery** [comment]
Thanks @whs it works great, and it is really helpful :)
now my kube-slack deployment, serviceaccount, clusterrole, clusterrolebinding  are identical to all clusters the only thing that changes is the environment vars secret: 
```
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: kube-system
type: Opaque
data:
  KUBE_CLUSTER_NAME: {{ kubernetes_cluster_name | b64encode }}
  KUBE_ARK_REPO_URL: {{ kubernetes_ark_repo_url | b64encode }} # hardcoded static var
  KUBE_SLACK_WEBHOOK_URL: {{ kubernetes_slack_webhook_url | b64encode }} # hardcoded static var
  KUBE_SLACK_CHANNEL: {{ kubernetes_slack_channel | b64encode }}
```
when kubernetes_slack_channel is "#k8s_{{ kubernetes_cluster_name.split('.')[0] }}_events".
